import { StyleSheet } from 'react-native';

export const BOOKING_COLORS = {
  background: '#fff',
  headerText: '#000',
  cardBorder: '#E0E0E0',
  bikeName: '#222',
  bikeTypeBadge: '#FFE082',
  bikeTypeText: '#222',
  bikeRate: '#222',
  sectionTitle: '#222',
  datePickerIcon: '#1F49D1',
  datePickerText: '#222',
  overviewDivider: '#E0E0E0',
  overviewLabel: '#888',
  overviewValue: '#222',
  overviewTotalLabel: '#222',
  overviewTotalValue: '#222',
  addButton: '#1F49D1',
  addButtonText: '#fff',
  modalOverlay: 'rgba(0,0,0,0.2)',
  confirmationModal: '#fff',
  confirmationTitle: '#222',
  confirmationSubtitle: '#222',
  confirmationBikeName: '#222',
  confirmationBadge: '#FFE082',
  confirmationBadgeText: '#222',
  confirmationButton: '#1F49D1',
  confirmationButtonText: '#fff',
};

export const BOOKING_RADIUS = {
  card: 30,
  bikeImage: 12,
  bikeTypeBadge: 12,
  addButton: 24,
  confirmationModal: 20,
  confirmationBadge: 12,
  confirmationButton: 16,
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BOOKING_COLORS.background },
  scrollContent: { padding: 20, paddingBottom: 100 },
  headerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20, position: 'relative', height: 60 },
  backButton: { marginBottom: 0, marginRight: 16, borderColor: BOOKING_COLORS.cardBorder, borderWidth: 1, zIndex: 2 },
  backIcon: { width: 24, height: 24, tintColor: BOOKING_COLORS.bikeName },
  title: { position: 'absolute', left: 0, right: 0, textAlign: 'center', fontSize: 34, fontWeight: 'bold', color: BOOKING_COLORS.headerText, zIndex: 1, fontFamily: 'Mont' },
  bikeCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: BOOKING_COLORS.background, borderRadius: BOOKING_RADIUS.card, padding: 16, marginBottom: 20, borderWidth: 1, borderColor: BOOKING_COLORS.cardBorder },
  bikeImage: { width: 80, height: 80, borderRadius: BOOKING_RADIUS.bikeImage, marginRight: 16, backgroundColor: '#eee' },
  bikeInfo: { flex: 1 },
  bikeName: { fontSize: 18, fontWeight: 'bold', color: BOOKING_COLORS.bikeName, fontFamily: 'Mont' },
  bikeTypeBadge: { backgroundColor: BOOKING_COLORS.bikeTypeBadge, borderRadius: BOOKING_RADIUS.bikeTypeBadge, paddingHorizontal: 10, paddingVertical: 2, alignSelf: 'flex-start', marginVertical: 4 },
  bikeTypeText: { color: BOOKING_COLORS.bikeTypeText, fontWeight: '600', fontSize: 12, fontFamily: 'Mont' },
  bikeRateContainer: { flexDirection: 'row', flexWrap: 'wrap' },
  bikeRate: { fontSize: 18, color: BOOKING_COLORS.bikeRate, marginTop: 4, fontWeight: 'bold', fontFamily: 'Mont' },
  bikeRateUnit: { fontSize: 18, color: BOOKING_COLORS.bikeRate, marginTop: 4, fontFamily: 'Mont'},
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginTop: 20, marginBottom: 10, color: BOOKING_COLORS.sectionTitle, fontFamily: 'Mont' },
  datePicker: { backgroundColor: BOOKING_COLORS.background, borderRadius: 30, padding: 16, flexDirection: 'row', alignItems: 'center', marginBottom: 20, borderWidth: 1, borderColor: BOOKING_COLORS.cardBorder },
  datePickerUnconfirmed: { borderColor: '#FFD775', borderWidth: 2 },
  calendarIcon: { width: 24, height: 24, marginRight: 10, tintColor: BOOKING_COLORS.datePickerIcon },
  datePickerText: { fontSize: 16, color: BOOKING_COLORS.datePickerText, fontFamily: 'Mont' },
  overviewDivider: { height: 1, backgroundColor: BOOKING_COLORS.overviewDivider, marginBottom: 10 },
  overviewRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  overviewLabel: { color: BOOKING_COLORS.overviewLabel, fontSize: 14, fontFamily: 'Mont' },
  overviewValue: { color: BOOKING_COLORS.overviewValue, fontSize: 14, fontFamily: 'Mont' },
  overviewTotalLabel: { color: BOOKING_COLORS.overviewTotalLabel, fontWeight: 'bold', fontSize: 16, fontFamily: 'Mont' },
  overviewTotalValue: { color: BOOKING_COLORS.overviewTotalValue, fontWeight: 'bold', fontSize: 24, fontFamily: 'Mont' },
  addButton: { backgroundColor: BOOKING_COLORS.addButton, borderRadius: BOOKING_RADIUS.addButton, margin: 20, paddingVertical: 18, alignItems: 'center', justifyContent: 'center' },
  addButtonText: { color: BOOKING_COLORS.addButtonText, fontSize: 16, fontWeight: 'bold', fontFamily: 'Mont' },
  modalOverlay: { flex: 1, backgroundColor: BOOKING_COLORS.modalOverlay, justifyContent: 'center', alignItems: 'center' },
  confirmationModal: { backgroundColor: BOOKING_COLORS.confirmationModal, borderRadius: BOOKING_RADIUS.confirmationModal, padding: 24, alignItems: 'center', width: '90%' },
  confirmationTitle: { fontSize: 24, fontWeight: 'bold', color: BOOKING_COLORS.confirmationTitle, marginBottom: 8, fontFamily: 'Mont' },
  confirmationSubtitle: { fontSize: 16, color: BOOKING_COLORS.confirmationSubtitle, marginBottom: 16, fontFamily: 'Mont' },
  confirmationImage: { width: 120, height: 120, resizeMode: 'contain', marginBottom: 16 },
  confirmationBikeName: { fontSize: 18, fontWeight: 'bold', color: BOOKING_COLORS.confirmationBikeName, marginBottom: 8, fontFamily: 'Mont' },
  confirmationBadge: { backgroundColor: BOOKING_COLORS.confirmationBadge, borderRadius: BOOKING_RADIUS.confirmationBadge, paddingHorizontal: 10, paddingVertical: 4, marginBottom: 24 },
  confirmationBadgeText: { color: BOOKING_COLORS.confirmationBadgeText, fontWeight: '600', fontSize: 14, fontFamily: 'Mont' },
  confirmationButton: { backgroundColor: BOOKING_COLORS.confirmationButton, borderRadius: BOOKING_RADIUS.confirmationButton, paddingVertical: 16, paddingHorizontal: 32, alignItems: 'center', marginTop: 8 },
  confirmationButtonText: { color: BOOKING_COLORS.confirmationButtonText, fontWeight: 'bold', fontSize: 18, fontFamily: 'Mont' },
}); 